# Generated by Django 5.0.1 on 2024-02-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_is',
            field=models.CharField(default='normal', max_length=50),
        ),
    ]
