# Generated by Django 5.0.1 on 2024-02-09 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0003_alter_game_game_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='opponent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Opponent_player', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Game_Creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
