# Generated by Django 5.0.1 on 2024-02-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0005_alter_game_opponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='move_history',
            field=models.TextField(default=''),
        ),
    ]
