# Generated by Django 5.0.1 on 2024-02-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0008_alter_game_opponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='move_history',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
