# Generated by Django 5.0.1 on 2024-02-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0010_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='other_side',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
