# Generated by Django 5.0.1 on 2024-02-15 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0012_alter_game_fen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='move_history',
        ),
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
